table 'Fact Bank Transactions'
	lineageTag: 24f86956-59b2-4e10-a649-d147e9a99a42

	measure 'Total bank transactions' = COUNTROWS('Fact Bank Transactions')
		lineageTag: f1fe6aaa-79f7-4282-9e40-5ce2a4fc0f3e

		formatStringDefinition = DaxLib.FormatString.Basic.RomanNumerals()

	measure 'Total income' = CALCULATE(SUM('Fact Bank Transactions'[Amount]), 'Dim Transaction Info'[is_income] = "Yes")
		lineageTag: 6a328592-3e5a-49d9-85ac-6a365515be8d

		formatStringDefinition = DaxLib.FormatString.DynamicUnits(SELECTEDMEASURE(), "€", "PREFIX", "", "")

	measure 'Total expenses' = CALCULATE(SUM('Fact Bank Transactions'[Amount]), 'Dim Transaction Info'[is_expense] = "Yes")
		lineageTag: 940b5f05-6772-4be5-a90c-4664821739c9

		formatStringDefinition = DaxLib.FormatString.DynamicUnits(SELECTEDMEASURE(), "€", "PREFIX", "", "")

	measure 'Text - Filtered date period' = PiotrBartela.TitleContext.Period("Monthly budget of ", 'Dim Date'[Date])
		lineageTag: 9bad3b1d-10ef-420c-bb95-be20e4a0c95d

	measure 'Net balance' = [Total income] - [Total expenses]
		lineageTag: 16addda9-0175-45bf-aac9-fc52faa4efbb

		formatStringDefinition = DaxLib.FormatString.DynamicUnits(SELECTEDMEASURE(), "€", "PREFIX", "", "")

	measure 'Net balance Previous Month' = CALCULATE([Net balance], PREVIOUSMONTH('Dim Date'[Date]))
		lineageTag: 1e9d9d12-da4c-498f-bf40-cdf8826031c7

		formatStringDefinition = DaxLib.FormatString.DynamicUnits(SELECTEDMEASURE(), "€", "PREFIX", "", "")

	measure 'Total income previous month' = Jespervb7.TimeIntelligence._PreviousMonth([Total income])
		lineageTag: 3e07d1a0-6d2e-4e8c-bf31-17879b620787

		formatStringDefinition = DaxLib.FormatString.DynamicUnits(SELECTEDMEASURE(), "€", "PREFIX", "", "")

	measure 'Total expenses previous month' = Jespervb7.TimeIntelligence._PreviousMonth([Total expenses])
		lineageTag: 4572a08a-4d99-4712-b568-3fbbfe9a71e1

		formatStringDefinition = DaxLib.FormatString.DynamicUnits(SELECTEDMEASURE(), "€", "PREFIX", "", "")

	measure '%Δ Income diff PM' = Jespervb7.PercentDifference([Total income], [Total income previous month])
		lineageTag: 12066c0c-1c0e-4a30-b70e-8071c7564da8

		formatStringDefinition = DaxLib.FormatString.RelativeToTarget.Percents("PREFIX", 1, "TRIANGLES", "", "")

	measure 'Expenses PY' = CALCULATE([Total expenses], PREVIOUSMONTH('Dim Date'[Date SK]))
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: b93646e8-8207-45be-8df8-9785d7751120

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Total expenses day level PM' = CALCULATE([Total expenses], DATEADD('Dim Date'[Date], -1, MONTH))
		lineageTag: 4fdeaecc-27a4-4509-8a3d-2f09626257a2

		formatStringDefinition = DaxLib.FormatString.DynamicUnits(SELECTEDMEASURE(), "€", "PREFIX", "", "")

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Text - Filtered date period - tooltip' = PiotrBartela.TitleContext.Period("Expenses of ", 'Dim Date'[Date])
		lineageTag: 1db3856c-4285-4de2-b2c0-d4a56544b120

	measure 'Total amount' = SUM('Fact Bank Transactions'[Amount])
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: e6897b50-5b30-4be0-abf9-53957d3b3384

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column company_sk
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 5d7700d5-1c8f-4224-a461-822a7e596037
		summarizeBy: none
		sourceColumn: company_sk

		annotation SummarizationSetBy = Automatic

	column transaction_info_sk
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 3b5f9de5-bdec-4dfe-8e5a-22523653811d
		summarizeBy: none
		sourceColumn: transaction_info_sk

		annotation SummarizationSetBy = Automatic

	column received_date_sk
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 118b1a14-75d7-4368-bf3a-2a21340b513a
		summarizeBy: none
		sourceColumn: received_date_sk

		annotation SummarizationSetBy = Automatic

	column counterparty
		dataType: string
		lineageTag: fb0a5b2d-cc0d-4ecf-9e9f-08f4572aba88
		summarizeBy: none
		sourceColumn: counterparty

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: decimal
		isHidden
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 9d843dc6-2a26-426a-a30a-21e852db6450
		summarizeBy: none
		sourceColumn: amount_in_euro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	partition 'Fact Bank Transactions' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(Filepath & "Fact_bank_transactions.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"company_sk", Int64.Type}, {"transaction_info_sk", Int64.Type}, {"received_date_sk", Int64.Type}, {"counterparty", type text}, {"amount_in_euro", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

