table 'Fact bank transactions'
	lineageTag: 0fe190bb-6707-4704-82d3-64d10e79a854

	measure 'Incoming transaction' = CALCULATE(SUM('Fact bank transactions'[Amount (EUR)]), 'Fact bank transactions'[Type of transaction] = "Incoming transaction")
		formatString: € #,##0.00
		lineageTag: 08bda2fd-25db-47cb-ad5e-a282ecc02b51

		annotation PBI_FormatHint = {"isCustom":true}

	measure Amount = sum('Fact bank transactions'[Amount (EUR)])
		formatString: € #,##0.00
		lineageTag: f0d0167d-0e58-44a1-b394-b9dff8921e0b

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Outgoing transaction' = CALCULATE(SUM('Fact bank transactions'[Amount (EUR)]), 'Fact bank transactions'[Type of transaction] = "Outgoing transaction")
		formatString: € #,##0.00
		lineageTag: 39170308-f8a7-4307-b9aa-89f744c66cf9

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Name / Description'
		dataType: string
		lineageTag: 2356fc41-9db6-454f-aa1c-f827eff2c863
		summarizeBy: none
		sourceColumn: Name / Description

		annotation SummarizationSetBy = Automatic

	column Account
		dataType: string
		lineageTag: 3fcd9dca-30d0-465e-9311-a51788b45e64
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column Counterparty
		dataType: string
		lineageTag: 05a19a9f-a88f-4983-8e67-101e16821ca7
		summarizeBy: none
		sourceColumn: Counterparty

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: dcbfb1f2-a649-48f6-8463-b98f04bd6141
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Debit/credit
		dataType: string
		lineageTag: 93b64dbc-00a2-47ea-9148-01950cc951cd
		summarizeBy: none
		sourceColumn: Debit/credit

		annotation SummarizationSetBy = Automatic

	column 'Amount (EUR)'
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 2e018a78-f155-4279-884d-33491e6720eb
		summarizeBy: sum
		sourceColumn: Amount (EUR)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Transaction type'
		dataType: string
		lineageTag: 5a7101ee-a5b0-4e6b-a28c-e5bd3674f838
		summarizeBy: none
		sourceColumn: Transaction type

		annotation SummarizationSetBy = Automatic

	column Notifications
		dataType: string
		lineageTag: e8d5d05f-089b-4162-992e-1b807bdfd88c
		summarizeBy: none
		sourceColumn: Notifications

		annotation SummarizationSetBy = Automatic

	column 'Resulting balance'
		dataType: string
		lineageTag: 4ac354d6-4988-40df-a16c-be6847c026c2
		summarizeBy: none
		sourceColumn: Resulting balance

		annotation SummarizationSetBy = Automatic

	column Tag
		dataType: string
		lineageTag: 99dfdc38-b091-436e-8d88-170318ada70c
		summarizeBy: none
		sourceColumn: Tag

		annotation SummarizationSetBy = Automatic

	column 'Hash value'
		dataType: string
		lineageTag: b93c2bb9-6094-4114-8184-6584839ef0ed
		summarizeBy: none
		sourceColumn: Hash value

		annotation SummarizationSetBy = Automatic

	column 'Hash banking identification'
		dataType: string
		lineageTag: d7b18269-0716-4f46-9b58-a851b9e30a64
		summarizeBy: none
		sourceColumn: Hash banking identification

		annotation SummarizationSetBy = Automatic

	column 'Type of transaction'
		dataType: string
		lineageTag: abd66904-123d-4b66-9cfb-53f25322a816
		summarizeBy: none
		sourceColumn: Type of transaction

		annotation SummarizationSetBy = Automatic

	column company_name
		dataType: string
		lineageTag: 891f78ed-1614-488f-b4c2-da188c9b74d9
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column 'Date ID'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 84af8d97-5ccb-47ce-9c82-d9103e24e057
		summarizeBy: none
		sourceColumn: Date ID

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Fact bank transactions' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\git\PowerBI-Dashboard-Portfolio\data\Finances_Anonymized.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Inserted Date" = Table.AddColumn(#"Promoted Headers", "Date.1", each Date.From(Text.From([Date], "en-GB")), type date),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Date",{{"Date.1", "Date ID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Date", "Date ID", "Name / Description", "Account", "Counterparty", "Code", "Debit/credit", "Amount (EUR)", "Transaction type", "Notifications", "Resulting balance", "Tag", "Hash value", "Hash banking identification", "Type of transaction", "company_name"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Date"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Name / Description", type text}, {"Account", type text}, {"Counterparty", type text}, {"Code", type text}, {"Debit/credit", type text}, {"Amount (EUR)", Currency.Type}, {"Transaction type", type text}, {"Notifications", type text}, {"Resulting balance", type text}, {"Tag", type text}, {"Hash value", type text}, {"Hash banking identification", type text}, {"Type of transaction", type text}, {"company_name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

