// Write your formula below, select 'Run' to try it out. When ready, select 'Update model' to add the measure to your model.
DEFINE
	MEASURE 'Fact Bank Transactions'[New Measure] = COUNTROWS('Fact Bank Transactions')

EVALUATE
	SUMMARIZECOLUMNS(
		'Dim Date'[Year],
		'Dim Transaction Info'[is_fastfood],
		FILTER('Dim Transaction Info', 'Dim Transaction Info'[is_fastfood] = "Yes"),
		"test", [New Measure]
	)