DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"Achmea"}, 'Dim Company'[company_name])

	VAR __DS0FilterTable2 = 
		FILTER(KEEPFILTERS(VALUES('Dim Date'[Year])), 'Dim Date'[Year] = 2023)

EVALUATE
	SUMMARIZECOLUMNS(
		__DS0FilterTable,
		__DS0FilterTable2,
		"Total_income", IGNORE('Fact Bank Transactions'[Total income]),
		"v_Total_income_FormatString", IGNORE('Fact Bank Transactions'[_Total income FormatString])
	)