// Write your formula below, select 'Run' to try it out. When ready, select 'Update model' to add the measure to your model.
DEFINE
	MEASURE 'Fact Bank Transactions'[Delta] = COUNTROWS('Fact Bank Transactions')

EVALUATE
	SUMMARIZECOLUMNS(
		"New Measure", [New Measure]
	)