name: Run BPA on Semantic Models and Reports
  
on:

  # push:
  #   branches:
  #     - main           
  #   paths:
  #     - '**/*.Report/**'
  #     - '**/*.SemanticModel/**'  

  pull_request:
    branches: 
      - main      
    paths:
      - '**/*.Report/**'
      - '**/*.SemanticModel/**'
  
  workflow_dispatch:
        
jobs:
  
  bpa:   
    runs-on: windows-latest
    
    steps:
        - name: Check out the repository
          # This step checks out the repository so that the workflow can access its contents.
          # Using v4 of the checkout action for better performance and features.
          uses: actions/checkout@v4

        - name: BPA Semantic Models
          run: .\ci_cd\bpa\bpa.ps1 -src @("./dashboards/*.SemanticModel")
      
        # - name: BPA Reports
        #   run: .\.bpa\bpa.ps1 -src @("./src/*/*/*.Report")